// <auto-generated />
using System;
using InterviewPanelManagementTool.Infrastructure.DataConfiguration.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterviewPanelManagementTool.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251227061035_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InterviewPanelManagementTool.Domain.Entities.Candidate", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CandidateId"));

                    b.Property<int>("CandidateCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<int>("PracticeId")
                        .HasColumnType("int");

                    b.HasKey("CandidateId");

                    b.HasIndex("CandidateCode")
                        .IsUnique();

                    b.HasIndex("PositionId");

                    b.HasIndex("PracticeId");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("InterviewPanelManagementTool.Domain.Entities.InterviewBooking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<int>("AvailabilityId")
                        .HasColumnType("int");

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<int>("PracticeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("AdminId");

                    b.HasIndex("AvailabilityId")
                        .IsUnique();

                    b.HasIndex("CandidateId");

                    b.HasIndex("MemberId");

                    b.HasIndex("PositionId");

                    b.HasIndex("PracticeId");

                    b.ToTable("InterviewBookings");
                });

            modelBuilder.Entity("InterviewPanelManagementTool.Domain.Entities.MemberAvailability", b =>
                {
                    b.Property<int>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvailabilityId"));

                    b.Property<int>("AvailabilityStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("AvailabilityId");

                    b.HasIndex("MemberId", "Date", "StartTime", "EndTime")
                        .IsUnique();

                    b.ToTable("MemberAvailabilities", t =>
                        {
                            t.HasCheckConstraint("CK_MemberAvailability_Time", "[EndTime] > [StartTime]");
                        });
                });

            modelBuilder.Entity("InterviewPanelManagementTool.Domain.Entities.MemberPosition", b =>
                {
                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.HasKey("MemberId", "PositionId");

                    b.HasIndex("PositionId");

                    b.ToTable("MemberPositions");
                });

            modelBuilder.Entity("InterviewPanelManagementTool.Domain.Entities.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PracticeId")
                        .HasColumnType("int");

                    b.HasKey("PositionId");

                    b.HasIndex("PracticeId", "PositionName")
                        .IsUnique();

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("InterviewPanelManagementTool.Domain.Entities.Practice", b =>
                {
                    b.Property<int>("PracticeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PracticeId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PracticeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PracticeId");

                    b.HasIndex("PracticeName")
                        .IsUnique();

                    b.ToTable("Practices");
                });

            modelBuilder.Entity("InterviewPanelManagementTool.Domain.Entities.RescheduleRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("NewEndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("NewStartTime")
                        .HasColumnType("time");

                    b.Property<int?>("ProcessedByAdminId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("ProposedDate")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RequestId");

                    b.HasIndex("BookingId");

                    b.HasIndex("MemberId");

                    b.HasIndex("ProcessedByAdminId");

                    b.ToTable("RescheduleRequests");
                });

            modelBuilder.Entity("InterviewPanelManagementTool.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("DesignationPositionId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("bit");

                    b.Property<string>("Passwordhash")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("PracticeId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DesignationPositionId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PracticeId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InterviewPanelManagementTool.Domain.Entities.Candidate", b =>
                {
                    b.HasOne("InterviewPanelManagementTool.Domain.Entities.Position", "Position")
                        .WithMany("Candidates")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InterviewPanelManagementTool.Domain.Entities.Practice", "Practice")
                        .WithMany("Candidates")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("Practice");
                });

            modelBuilder.Entity("InterviewPanelManagementTool.Domain.Entities.InterviewBooking", b =>
                {
                    b.HasOne("InterviewPanelManagementTool.Domain.Entities.User", "Admin")
                        .WithMany("InterviewBookingsByAdmin")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InterviewPanelManagementTool.Domain.Entities.MemberAvailability", "Availability")
                        .WithOne("Booking")
                        .HasForeignKey("InterviewPanelManagementTool.Domain.Entities.InterviewBooking", "AvailabilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InterviewPanelManagementTool.Domain.Entities.Candidate", "Candidate")
                        .WithMany("InterviewBookings")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InterviewPanelManagementTool.Domain.Entities.User", "Member")
                        .WithMany("BookingsForMember")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InterviewPanelManagementTool.Domain.Entities.Position", "Position")
                        .WithMany("InterviewBookings")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InterviewPanelManagementTool.Domain.Entities.Practice", "Practice")
                        .WithMany("InterviewBookings")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Availability");

                    b.Navigation("Candidate");

                    b.Navigation("Member");

                    b.Navigation("Position");

                    b.Navigation("Practice");
                });

            modelBuilder.Entity("InterviewPanelManagementTool.Domain.Entities.MemberAvailability", b =>
                {
                    b.HasOne("InterviewPanelManagementTool.Domain.Entities.User", "Member")
                        .WithMany("MemberAvailabilities")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("InterviewPanelManagementTool.Domain.Entities.MemberPosition", b =>
                {
                    b.HasOne("InterviewPanelManagementTool.Domain.Entities.User", "Member")
                        .WithMany("MemberPositions")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InterviewPanelManagementTool.Domain.Entities.Position", "Position")
                        .WithMany("MemberPositions")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("InterviewPanelManagementTool.Domain.Entities.Position", b =>
                {
                    b.HasOne("InterviewPanelManagementTool.Domain.Entities.Practice", "Practice")
                        .WithMany("Positions")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Practice");
                });

            modelBuilder.Entity("InterviewPanelManagementTool.Domain.Entities.RescheduleRequest", b =>
                {
                    b.HasOne("InterviewPanelManagementTool.Domain.Entities.InterviewBooking", "Booking")
                        .WithMany("RescheduleRequests")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InterviewPanelManagementTool.Domain.Entities.User", "Member")
                        .WithMany("MemberRescheduleRequests")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InterviewPanelManagementTool.Domain.Entities.User", "ProcessedByAdmin")
                        .WithMany("ProcessedRescheduleRequests")
                        .HasForeignKey("ProcessedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Booking");

                    b.Navigation("Member");

                    b.Navigation("ProcessedByAdmin");
                });

            modelBuilder.Entity("InterviewPanelManagementTool.Domain.Entities.User", b =>
                {
                    b.HasOne("InterviewPanelManagementTool.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedUsers")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InterviewPanelManagementTool.Domain.Entities.Position", "DesignationPosition")
                        .WithMany()
                        .HasForeignKey("DesignationPositionId");

                    b.HasOne("InterviewPanelManagementTool.Domain.Entities.Practice", "Practice")
                        .WithMany("Members")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("DesignationPosition");

                    b.Navigation("Practice");
                });

            modelBuilder.Entity("InterviewPanelManagementTool.Domain.Entities.Candidate", b =>
                {
                    b.Navigation("InterviewBookings");
                });

            modelBuilder.Entity("InterviewPanelManagementTool.Domain.Entities.InterviewBooking", b =>
                {
                    b.Navigation("RescheduleRequests");
                });

            modelBuilder.Entity("InterviewPanelManagementTool.Domain.Entities.MemberAvailability", b =>
                {
                    b.Navigation("Booking");
                });

            modelBuilder.Entity("InterviewPanelManagementTool.Domain.Entities.Position", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("InterviewBookings");

                    b.Navigation("MemberPositions");
                });

            modelBuilder.Entity("InterviewPanelManagementTool.Domain.Entities.Practice", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("InterviewBookings");

                    b.Navigation("Members");

                    b.Navigation("Positions");
                });

            modelBuilder.Entity("InterviewPanelManagementTool.Domain.Entities.User", b =>
                {
                    b.Navigation("BookingsForMember");

                    b.Navigation("CreatedUsers");

                    b.Navigation("InterviewBookingsByAdmin");

                    b.Navigation("MemberAvailabilities");

                    b.Navigation("MemberPositions");

                    b.Navigation("MemberRescheduleRequests");

                    b.Navigation("ProcessedRescheduleRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
